# Dave Ruiz Design

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: your-email@domain.com

# SEO/Meta
title: Dave Ruiz
description: I'm an experienced Digital Product Designer based in Canada, and I have a strong passion for UX and visual design.

# Hero
hero:
  heading: UX Design
  subheading: I'm an experienced Digital Product Designer based in Canada, and I have a strong passion for UX and visual design.

# History
history:
  heading: My history
  subheading: I've been fortunate enough to work with some really great teams.

# Availability (Colors: Red, Green, Yellow)
availability:
  text: Accepting new projects on a limited basis.
  color: yellow

# Quote
quote:
  heading: Quotes
  text: Dave is a consummate professional and a expert in user experience on the web. Unlike so many designers, he spends the time to understand your business goals and needs. With Dave, the design is always a vehicle to grow your business and to reduce friction for your users. The rarity and value of the skills he possesses cannot be overstated.
  source:
    name: J. M. Davis - President
    company: Scrapbook.com

# Copyright
copyright: © 2016 Dave Ruiz. <span class="copyright--dont-steal">Please don’t steal.</span>

# Social links
twitter_username: jekyllrb



# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed



# Collections
collections:
  jobs:
    output: true
  portfolio:
    output: true
